FROM node:22-alpine
WORKDIR /app
RUN apk add --no-cache bash
COPY package*.json ./
RUN npm ci
COPY tsconfig.json ./
COPY tsconfig.build.json ./
COPY . .
EXPOSE 3000
ENV NODE_ENV=development
CMD ["npx","tsx","watch","src/index.ts"]
