[protocol]
name = "ekklesia-hydra"
scope = "vote.ekklesia"
version = "0.0.1"
description = "Manage the Hydra interface for Ekklesia instances"
main = "main.tx3"

[ledger]
family = "cardano"

[[codegen]]
plugin = "ts-client"
