// This file is auto-generated by trix bindgen.

import {
    TRPClient,
    type ArgValue,
    type ClientOptions,
    type SubmitParams,
    type ResolveResponse,
} from "tx3-sdk/trp";


export const DEFAULT_TRP_ENDPOINT = "http://localhost:8164";

export const DEFAULT_HEADERS = {
};

export const DEFAULT_ENV_ARGS = {
};

export type TransferParams = {
    quantity: ArgValue | bigint | number; // Int
    receiver: ArgValue | string; // Address
    sender: ArgValue | string; // Address
}

export const TRANSFER_IR = {
    bytecode: "0d03000106736f757263650d0206736f757263650d010673656e646572050e010c0100000d01087175616e74697479020d0300000000020d0108726563656976657205000c0100000d01087175616e74697479020d010673656e64657205000e020e0210010d0206736f757263650d010673656e646572050e010c0100000d01087175616e74697479020d030000000c0100000d01087175616e74697479020d0300000000000000",
    encoding: "hex",
    version: "v1alpha8",
};

export class Client {
    readonly #client: TRPClient;

    constructor(options: ClientOptions) {
        this.#client = new TRPClient(options);
    }

    async transferTx(args: TransferParams): Promise<ResolveResponse> {
        return await this.#client.resolve({
            tir: TRANSFER_IR,
            args,
        });
    }

    async submit(params: SubmitParams): Promise<void> {
        await this.#client.submit(params);
    }
}

// Create a default client instance
export const protocol = new Client({
    endpoint: DEFAULT_TRP_ENDPOINT,
    headers: DEFAULT_HEADERS,
    envArgs: DEFAULT_ENV_ARGS,
});
